framework:
    secret: '%env(APP_SECRET)%'

    # Sessions
    session: true

    trusted_proxies: '172.16.0.0/12'
    trusted_headers:
        - x-forwarded-for
        - x-forwarded-proto
        - x-forwarded-port
        - x-forwarded-host

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file